### PR TITLE
docs/introduction/clojure-in-15-minutes.md: s/def/defn/g for functions; fix various formatting issues

### PR DESCRIPTION
**Pull request by jf**

### CODE REVIEW

**Comment by practicalli-john** [comment]
This whole page needs a bit of an update and improved formatting styles.  Thanks for highlighting this.

**Comment by jf** [comment]
Do you want to take a look at the specific fixes I bring up here again? I do not see them being fixed with 84cff16.

To call out the 2 that really need fixing:

1. the formatting for this code sample:
Screenshot 2023-09-22 at 23 58 57

2. `defn` for functions instead of `def`

**Comment by practicalli-john** [comment]
Sure, any improvements to code examples is welcome...  this was written several years ago.

**Comment by jf** [comment]
closing this now, since I see that with the new copy of the page, my issues are addressed.

**Pull request closed without merging**
